### ISSUE TITLE
Invalid resource group location when example's setting different from default on Azure docker-based cluster

### ISSUE THREAD

**Issue by HongW2019** [oap-project/cloudtik#44]
When create a docker-based cluster on Azure.

example.yaml 
```
# Cloud-provider specific configuration.
provider:
    type: azure
    region: westus
```
default.yaml
```
# Cloud-provider specific configuration.
provider:
    type: azure
    location: westus2
```
Encounter an exception as below
```
Cluster: docker

Checking Azure environment settings
2022-04-01 09:36:00,456 INFO config.py:60 -- Using subscription id: ......
2022-04-01 09:36:00,456 INFO config.py:73 -- Creating/Updating Resource Group: intelML
Traceback (most recent call last):
  File "/root/miniconda2/envs/azure/bin/cloudtik", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/cloudtik/scripts/scripts.py", line 1444, in main
    return cli()
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/cloudtik/core/_private/cli_logger.py", line 807, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/cloudtik/scripts/scripts.py", line 480, in up
    use_login_shells=use_login_shells)
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/cloudtik/core/_private/cluster/cluster_operator.py", line 236, in create_or_update_cluster
    config = _bootstrap_config(config, no_config_cache=no_config_cache)
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/cloudtik/core/_private/cluster/cluster_operator.py", line 322, in _bootstrap_config
    resolved_config = provider_cls.bootstrap_config(config)
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/cloudtik/providers/_private/_azure/node_provider.py", line 341, in bootstrap_config
    return bootstrap_azure(cluster_config)
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/cloudtik/providers/_private/_azure/config.py", line 41, in bootstrap_azure
    config = _configure_resource_group(config)
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/cloudtik/providers/_private/_azure/config.py", line 75, in _configure_resource_group
    resource_group_name=resource_group, parameters=params)
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/azure/mgmt/resource/resources/v2021_04_01/operations/_resource_groups_operations.py", line 158, in create_or_update
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/root/miniconda2/envs/azure/lib/python3.7/site-packages/azure/core/exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: (InvalidResourceGroupLocation) Invalid resource group location 'westus2'. The Resource group already exists in location 'westus'.
Code: InvalidResourceGroupLocation
Message: Invalid resource group location 'westus2'. The Resource group already exists in location 'westus'.
```

**Comment by jerrychenhf** [comment]
This is not a bug. In your example, you use:
region: westus

But for Azure, it should be:
location: westus

which means you didn't specify the location to westus and then use the default "westus2". But the resource group do belongs to westus. It reported the right error.

**Comment by HongW2019** [comment]
> This is not a bug. In your example, you use: region: westus
> 
> But for Azure, it should be: location: westus
> 
> which means you didn't specify the location to westus and then use the default "westus2". But the resource group do belongs to westus. It reported the right error.

Yes, this is not a bug, cloudtik reported the right error for my incorrect configuration of yaml. I will close it.
